### ISSUE TITLE
SF2: Incorrect loop indexes & Realtime: Missed note off events

### ISSUE THREAD

**Issue by KaleidonKep99** [BlackMIDIDevs/xsynth#80]
As the title says, the buffer does not seem to drop notes that have been played, and seems to get stuck playing them over and over again?

XSynth is the *only* engine that does not make use of OMv2's internal events buffer, instead it gets fed the events directly, so this is 100% an issue outside of OMv2.

https://github.com/user-attachments/assets/87ad214c-7b9c-4a21-9db4-81a8a16b4a3a

**Comment by KaleidonKep99** [comment]
> > The SoundFont is Piano Korg Triton, and yes it happened with OCv2 too.
> 
> Could you send me the soundfont? I can't recreate this with the one I have (plus it sounds a bit different) and I can't seem to find it online...
> 
> Btw this is two issues combined. One is missed note off events and the other is wrong loop indexes. But it's related to XSynth itself and not the CLib so I'll move the issue there.

Here it is, the almighty Korg.
[piano korg triton.zip](https://github.com/user-attachments/files/16483066/piano.korg.triton.zip)

**Comment by arduano** [comment]
Hey,

> I can make it so XSynth makes use of OMv2's events buffer too, if you want.

By event buffers do you mean the cyclic buffer that queues events up for the synth to process separately? I think xsynth's solution is a little better.

It has the following components:
- Each channel runs in its own thread. Each channel also provides an "event sender".
- The publicly exposed API has the "event senders" struct (plural). When sending an event to that, it decides if it's something to send to one channel or all channels, depending on the event type.
- The event sender uses a high performance message queue [crossbeam](https://crates.io/crates/crossbeam-channel) which is known to be very high performance (I've benchmarked it), and is definitely faster than anything we could make.
- The event sender has a custom NPS limiter designed to have minimal overhead (not querying system time for every event) while also filtering out events based on their velocity, lowest velocity first. It has a relatively high ceiling, and the nps window is about a second long. It's there to prevent the synth from being overloaded with extreme event spam that likely won't be audible anyway. 

I haven't had issues with the event senders, I'd be surprized if there's a bug that big in there, the bug is likely elsewhere

**Comment by MyBlackMIDIScore** [comment]
Wow ok I hadn't realized that the realtime module was so well thought out. Then the missed events most likely don't have to do with XSynth, rather magbe with PFA (because I assume that OM just sends whatever iy receives directly to XSynth), and the real issue here is the sample looping which is audible there.

**Comment by KaleidonKep99** [comment]
> Hey,
> 
> > I can make it so XSynth makes use of OMv2's events buffer too, if you want.
> 
> By event buffers do you mean the cyclic buffer that queues events up for the synth to process separately? I think xsynth's solution is a little better.

Yeah that is exactly why I decided to just wire OmniMIDI's short data functions directly to XSynth-clib's XSynth_ChannelGroup_SendEvent function, bypassing OMv2's internal events buffer.
